#lang racket
(define (make-interval a b) (cons a b))
(define (upper-bound interval) (cdr interval))
(define (lower-bound interval) (car interval))

(define (mul-interval x y)
  (let ((p1 (* (lower-bound x) (lower-bound y)))
        (p2 (* (lower-bound x) (upper-bound y)))
        (p3 (* (upper-bound x) (lower-bound y)))
        (p4 (* (upper-bound x) (upper-bound y))))
    (make-interval (min p1 p2 p3 p4)
                   (max p1 p2 p3 p4))))

(define (mul-interval x y) 
    (let ((xl (lower-bound x)) 
          (xu (upper-bound x)) 
          (yl (lower-bound y)) 
          (yu (upper-bound y))) 
      (cond ((>= xl 0) 
             (cond ((>= yl 0) 
                    (make-interval (* xl yl) (* xu yu))) 
                   ((<= yu 0) 
                    (make-interval (* xu yl) (* xl yu))) 
                   (else 
                    (make-interval (* xu yl) (* xu yu))))) 
            ((<= xu 0) 
             (cond ((>= yl 0) 
                    (make-interval (* xl yu) (* xu yl))) 
                   ((<= yu 0) 
                    (make-interval (* xu yu) (* xl yl))) 
                   (else 
                    (make-interval (* xl yu) (* xl yl))))) 
            (else 
             (cond ((>= yl 0) 
                    (make-interval (* xl yu) (* xu yu))) 
                   ((<= yu 0) 
                    (make-interval (* xu yl) (* xl yl))) 
                   (else 
                    (make-interval (min (* xl yu) (* xu yl)) 
                                   (max (* xl yl) (* xu yu)))))))))