#lang racket
(define (make-account balance secret-password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Недостаточно денег на счете"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Неизвестный вызов -- MAKE-ACCOUNT"
                       m))))
  (define counter 0)
  
  (define (deco-pass m pass)
    (if (eq? pass secret-password)
        (begin (set! counter 0) (dispatch m))
        (if (= counter 7)
            (error "call the cops")
            (begin (set! counter (+ counter 1)) (lambda (x) (display "wrong password \n"))))))
  deco-pass)

(define k (make-account 100 'wtf))


((k 'withdraw 'wtf) 5)
((k 'deposit 'wtf) 10)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'wtf) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)
((k 'deposit 'kfg) 3)